<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class AgentRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'name_company'=>'required',
            'number_save'=>'required',
            'number_economy'=>'required',
            'manage_agent'=>'required',
            'phone_manage'=>'required',
            'city_'=>'required',
            'city'=>'required',
            'phone_fixed'=>'required',
            'explain'=>'required',
            'file_name'=>'required|max:5000|mimes:jpg,jpeg,png,pdf,docx,doc,txt,zip,rar'
        ];
    }
    public function attributes()
    {
        //return parent::attributes();
        // T//ODO: Change the autogenerated stub
        return [
            //
            'name_company'=>'نام شرکت',
            'number_save'=>'شماره ثبت',
            'number_economy'=>'کد اقتصادی',
            'manage_agent'=>'نام مدیر عامل',
            'phone_manage'=>'شماره ',
            'city_'=>'استان',
            'city'=>'شهر',
            'phone_fixed'=>'شماره ثابت',
            'explain'=>'توضیحات',
            'file_name'=>'فایل آپلود شده'
        ];

    }
    public function messages()
    {
        return [
            //
            'required'=>':attribute به درستی وارد نشده است',
            'mimes' => ':attribute فقط نوع فایل های pdf,jpg,word,txt,zip,rar,zip می تواند باشد.',
            'max' => ':attribute نباید بیشتر از 5000 کیلو بایت باشد.',
        ];
    }
}